---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: /
    labels:
      - dependencies
      - workflows
    schedule:
      interval: daily
      time: "04:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
